name: movies

services:

    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
          - POSTGRES_DB=moviesAppDb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        
        