@base = https://localhost:7052

GET {{base}}/weatherforecast/
Accept: application/json

### get token
POST {{base}}/token
Content-Type: application/json

{
    "userId" : "0197352a-6645-73de-8990-e251d628a57e",
    "email" : "yogesh@gmail.com",
    "customClaims" : {
        "admin" : "true"
    }
}

###


